name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile-pwa/package-lock.json

      - name: Install dependencies
        run: |
          cd mobile-pwa
          npm ci

      - name: Build application
        run: |
          cd mobile-pwa
          npm run build
        env:
          NODE_ENV: production

      - name: Run tests (if available)
        run: |
          cd mobile-pwa
          npm test || echo "No tests configured"
        continue-on-error: true

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: './mobile-pwa/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions - ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10

      - name: Deployment summary
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "🌐 Your app is now live on Netlify"
          echo "📱 Mobile PWA ready for testing"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed"
          echo "Please check the logs above for details"
