name: SKIDS EYEAR - Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd admin-portal
          npm ci
      
      - name: Build application
        run: |
          cd admin-portal
          npm run build
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
      
      - name: Run Lighthouse CI
        run: |
          cd admin-portal
          lhci autorun --upload.target=temporary-public-storage || echo "Lighthouse CI failed"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      
      - name: Check performance budget
        run: |
          cd admin-portal
          echo "Checking performance budget..."
          # Performance checks would go here
